---
title: "PCA"
author: "Rheanna"
date: "2019年11月13日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
library("FactoMineR")
library("factoextra")
library(ggthemes)
library(ggsignif)
library(ggpubr)
library(car)

```


##data

```{r}

Sys.setenv(R_MAX_NUM_DLLS=999)
options(stringsAsFactors = F)  
#

design <- read.table("./design31.txt", header=T, row.names= 1, sep="\t")

alpha = read.table("../alpha_al20.txt", header=T, row.names= 1, sep="\t")

se <-read.table("../Fasting_map_all_beta_0223.txt",sep="\t",header=T,row.names=1)

alpha <- log1p(alpha)
env.data.log <- log1p(abs(se))
env <- na.omit(env.data.log)

index1 = cbind(alpha, env.data.log[match(rownames(alpha), rownames(env.data.log)), ])
index_all = cbind(design, index1[match(rownames(design), rownames(index1)), ])

index_new <- subset(index_all, group_Cu2 %in% c("soil1","soil2","Ms2","soil3","Ms3","ps3","p3") )

data_all <- index_new[,c("Description","shannon","Cr","Cu","Fe","Mn","Mo","Ni","P","Pb","pH","TN","TC","Cd","Amo.N","NOx.N")]
names(data_all)[1] <- "group"


# #X80Cu 和Q235对比2
 data1 <- subset(data_all, group %in% c("Q2352","X80Cu2","Q235s2", "X80Cus2"))
 data2 <- subset(data_all, group %in% c("Q2353","Q235s3" ,"X80Cu3", "X80Cus3","P","Ps"))
 data3 <-  subset(data_all, group %in% c("X80Cu1", "Q2351","P1"))
 
##X80Cu 和Q235对比3
 data1 <- subset(data_all, group %in% c("Q2352","Q235s2","Q2353","Q235s3","P","Ps" ))
 data2 <- subset(data_all, group %in% c("X80Cu2","X80Cus2","X80Cu3", "X80Cus3","P","Ps"))


```

```{r}
data <- data2
data_pca  <- data[,-1]


res.pca <- PCA(data_pca , graph = FALSE)
res.pca$eig
#
a1 <- fviz_contrib(res.pca, choice = "var", axes = 1:2, top = 10)
a1
```

```{r}
palette1 = c("#4682B4","#FF4500","#FFA500","#73BF00","darkred","#57C3C2","#426600")
# #palette1 = c("#FFA500","#2E8B57","#FF4500","#4682B4","#800080","#708090","#F5F5F5", "#FFA500","#2E8B57","#9ACD32","#808080","#778899","#20B2AA")
# 排序
# index_new$group_Cu2 <- ordered(index_new$group_Cu2, levels = c("soil1","soil2","Ms2","soil3","Ms3","p3","ps3"))
# 
# index_new$group_Cu <- ordered(index_new$group_Cu, levels = c("soil1","Q235","Q235s","X80Cu","X80Cus","p3","ps3"))

b <- fviz_pca_biplot(res.pca,arrowsize = 0.5, labelsize = 3,pointshape=21,pointsize=2,
                     fill.ind = as.factor(data$group),
                     addEllipses = FALSE, ellipse.level=0.8,label = "var",
                     repel = TRUE,xlim=c(-6,6),palette = palette1,col.var="gray50",
                     mean.point="false",xlab="PCA1 36.47%" ,ylab="PCA2 22.47%")
b
fontsize <- theme(axis.text=element_text(size=10), axis.title=element_text(size=12),title=(element_text(size=14)))
a <- ggpubr::ggpar(b,title = "Principal Component Analysis",ggtheme = theme_par()+fontsize+theme(legend.text = element_text(size=10)),ncol=2,legend.key.size=unit(1.2,"cm"))
a

#ggsave("./PCA plot of 201611.pdf",a,width=6,height=4)

```



```{r}
res.pca <- PCA(data_pca,scale.unit = TRUE, ncp = 5, graph = TRUE)
eig.val <-get_eigenvalue(res.pca)
fviz_eig(res.pca,addlabels=TRUE,ylim=c(0,50))
var <- get_pca_var(res.pca )
f <- fviz_pca_var(res.pca, col.var = "contrib",gradient.cols = palette1[2:4])
fontsize <- theme(axis.text=element_text(size=6), axis.title=element_text(size=8),title=(element_text(size=10)))
g <- ggpubr::ggpar(f,title = "Principal Component Analysis",ggtheme = theme_par()+fontsize+theme(legend.text = element_text(size=8)),ncol=2,legend.key.size=unit(1.2,"cm"),legend.title =element_text(size=8))
g
#ggsave("./201910/PCA plot of contri1107.pdf",g,width=5.5,height=4.5)

```

```{r}
ind <- get_pca_ind(res.pca)
ind
head(ind$coord)
# Quality of individuals
head(ind$cos2)
# Contributions of individuals
head(ind$contrib)

fviz_pca_ind(res.pca,col.ind="black",legend.title = list(fill="Samples"),mean.point="false",xlab="PC1 39.55%" ,ylab="PC2 19.54%")

```

```{r}
#env
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10)
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10)
fviz_contrib(res.pca, choice = "var", axes = 1:2, top = 10)

```

```{r}
library("corrplot")
corrplot(var$cos2, method="square",is.corr=FALSE,tl.cex=2,tl.col="black",number.cex = 2,number.font=1,cl.cex=2,cl.pos="r",cl.align.text="l" ,t1.cex=3)

```

```{r}
#距离差异检验 
library(vegan)

subindex = subset(data1, group %in% c("X80Cus2","X80Cu2"))

bray.dist_sample <- vegdist(subindex[,c(2:16)],method="bray")
bray.dist_sample <- as.matrix(bray.dist_sample)

adonis_table = adonis(bray.dist_sample~group, data=subindex, permutations = 999)

adonis_table$aov.tab
adonis_pvalue = adonis_table$aov.tab$`Pr(>F)`[1]
adonis_pvalue
```

##pairwise.adonis

```{r}
##factors可以是data1$group_Cu2，但是不可以是data1[1]

pairwise.adonis <- function(x,factors, sim.function = 'vegdist', sim.method = 'bray', p.adjust.m ='fdr')
{
library(vegan)

#不放回抽样,5个里面随机选出2个，C5 ^ 2事件
co = combn(unique(as.character(factors)),2)
pairs = c()
F.Model =c()
R2 = c()
p.value = c()


for(elem in 1:ncol(co)){
if(sim.function == 'daisy'){
library(cluster); x1 = daisy(x[factors %in% c(co[1,elem],co[2,elem]),],metric=sim.method)
} else{x1 = vegdist(x[factors %in% c(co[1,elem],co[2,elem]),],method=sim.method)}

ad = adonis(x1 ~ factors[factors %in% c(co[1,elem],co[2,elem])] );
pairs = c(pairs,paste(co[1,elem],'vs',co[2,elem]));
F.Model =c(F.Model,ad$aov.tab[1,4]);
R2 = c(R2,ad$aov.tab[1,5]);
p.value = c(p.value,ad$aov.tab[1,6])
}
p.adjusted = p.adjust(p.value,method=p.adjust.m)
sig = c(rep('',length(p.adjusted)))
sig[p.adjusted <= 0.05] <-'.'
sig[p.adjusted <= 0.01] <-'*'
sig[p.adjusted <= 0.001] <-'**'
sig[p.adjusted <= 0.0001] <-'***'

pairw.res = data.frame(pairs,F.Model,R2,p.value,p.adjusted,sig)
print("Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1")
return(pairw.res)

} 
```

```{r}
a <- pairwise.adonis(data1[,-1],data1$group)
write.table(file="./env_q235_pairwise.adonis.txt",a)

```


```{r}
#pairwise compare
observed_otus_stats <- aov(Mn ~  group_Cu2,data=data1)
Tukey_HSD_observed_otus <- TukeyHSD(observed_otus_stats, ordered = FALSE, conf.level = 0.95)
Tukey_HSD_observed_otus_table <- as.data.frame(Tukey_HSD_observed_otus$group_Cu2)
Tukey_HSD_observed_otus_table
```


```{r}

#用ANOSIM进行显著性分析（下例为比较A和B）
anosim(otu1,group,permutations = 999, distance = "bray")  
```

